apiVersion: apps/v1
kind: Deployment
metadata:
  name: praxis
spec:
  template:
    spec:
      containers:
        - name: praxis
          volumeMounts:
            - name: vertex-sa
              mountPath: /etc/vertex-sa
              readOnly: true
            - name: metering-internal-auth
              mountPath: /etc/praxis-secrets
              readOnly: true
      volumes:
        - name: vertex-sa
          secret:
            secretName: vertex-sa-key
        - name: metering-internal-auth
          secret:
            secretName: metering-internal-auth
